annotations:
  artifacthub.io/changes: |
    - description: Allow ConfigMap and Secret references in ``apiServer.env``
      kind: changed
      links:
      - name: '#51191'
        url: https://github.com/apache/airflow/pull/51191
    - description: Add custom annotations to JWT Secret
      kind: changed
      links:
      - name: '#52166'
        url: https://github.com/apache/airflow/pull/52166
    - description: Allow ``valuesFrom`` in ``gitSync.env``
      kind: changed
      links:
      - name: '#50228'
        url: https://github.com/apache/airflow/pull/50228
    - description: Fix JWT secret name
      kind: fixed
      links:
      - name: '#52268'
        url: https://github.com/apache/airflow/pull/52268
    - description: Use ``api-server`` instead of ``webserver`` in NOTES.txt for Airflow
        3.0+
      kind: fixed
      links:
      - name: '#52194'
        url: https://github.com/apache/airflow/pull/52194
    - description: Change default executor in pod template to support executor parameter
        in task
      kind: fixed
      links:
      - name: '#49433'
        url: https://github.com/apache/airflow/pull/49433
    - description: Use ``merged`` to render airflow.cfg and include computed defaults
      kind: fixed
      links:
      - name: '#51828'
        url: https://github.com/apache/airflow/pull/51828
    - description: Use ``[api] secret_key`` for Airflow 3.0+ instead of ``[webserver]
        secret_key``
      kind: fixed
      links:
      - name: '#52269'
        url: https://github.com/apache/airflow/pull/52269
    - description: Fix for ``fernetkey`` and add test of its value
      kind: fixed
      links:
      - name: '#52977'
        url: https://github.com/apache/airflow/pull/52977
    - description: 'Docs: Update supported executors in docs'
      kind: changed
      links:
      - name: '#52132'
        url: https://github.com/apache/airflow/pull/52132
    - description: 'Docs: Update service name for port-forward of Airflow UI'
      kind: changed
      links:
      - name: '#51945'
        url: https://github.com/apache/airflow/pull/51945
  artifacthub.io/links: |
    - name: Documentation
      url: https://airflow.apache.org/docs/helm-chart/1.18.0/
  artifacthub.io/screenshots: |
    - title: Home Page
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/home_dark.png
    - title: DAG Overview Dashboard
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/dag_overview_dashboard.png
    - title: DAGs View
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/dags.png
    - title: Assets View
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/asset_view.png
    - title: Grid View
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/dag_overview_grid.png
    - title: Graph View
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/dag_overview_graph.png
    - title: Variable View
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/variable_hidden.png
    - title: Code View
      url: https://airflow.apache.org/docs/apache-airflow/3.0.2/_images/dag_overview_code.png
apiVersion: v2
appVersion: 3.0.2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.24
description: The official Helm chart to deploy Apache Airflow, a platform to programmatically
  author, schedule, and monitor workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/images/airflow_dark_bg.png
keywords:
- apache
- airflow
- workflow
- scheduler
maintainers:
- email: dev@airflow.apache.org
  name: Apache Airflow PMC
name: airflow
sources:
- https://github.com/apache/airflow
type: application
version: 1.18.0
